[package]
name = "capi-parser"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
capi-ast.workspace = true
capi-diagnostics.workspace = true
capi-lexer.workspace = true
capi-source.workspace = true

[lints]
workspace = true
